=== Bcoast84/Lenguaje-de-marcas/pedidos.dtd
<!ELEMENT Pedidos (Pedido+)>
<!--definimos Pedido con sus elementos -->
<!ELEMENT Pedido (Sucursal, NombreTrabajador, FechaPedido, ObservacionesPedido?, PlazoRevision, Articulos)> 
    <!--definimos todos los elementos de Pedido -->
    <!ELEMENT Sucursal (DirEntrega+, (SedeCentral)?)>
    <!ELEMENT NombreTrabajador (#PCDATA)>
    <!ELEMENT FechaPedido (#PCDATA)>
    <!ELEMENT ObservacionesPedido (#PCDATA)>
    <!ELEMENT PlazoRevision (#PCDATA)>
    <!ELEMENT Articulos (Articulo+)>
    <!--definimos los elementos de Sucursal -->
    <!ELEMENT DirEntrega (#PCDATA)>
    <!ELEMENT SedeCentral EMPTY>
            <!-- A su vez, definimos artículo y sus elementos que estaran dentro de Articulos -->
            <!ELEMENT Articulo (UnidadesPedidas, PrecioUnidad, ObservacionesArt)>
            <!ELEMENT UnidadesPedidas (#PCDATA)>
            <!ELEMENT PrecioUnidad (#PCDATA)>
            <!ELEMENT ObservacionesArt (#PCDATA)>
        <!--Por último, definimos los atributos de Pedido y de Articulo -->
        <!ATTLIST Pedido CodigoPedido CDATA #REQUIRED>
        <!ATTLIST Articulo CodigoArt CDATA #REQUIRED>

=== Bcoast84/Lenguaje-de-marcas/pedido.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Pedidos SYSTEM "pedidos.dtd">

<Pedidos>
  <Pedido CodigoPedido="ABC123">
    <Sucursal>
      <DirEntrega>Direccion1</DirEntrega>
      <SedeCentral/>
    </Sucursal>  
    <NombreTrabajador>Juan Perez</NombreTrabajador>
    <FechaPedido>2024-03-05</FechaPedido>
    <ObservacionesPedido>Urgente</ObservacionesPedido>
    <PlazoRevision>7 días</PlazoRevision>
      <Articulos>
        <Articulo CodigoArt="ABD-123">
            <UnidadesPedidas>10</UnidadesPedidas>
            <PrecioUnidad>20.00</PrecioUnidad>
            <ObservacionesArt>Artículo de alta demanda</ObservacionesArt>
        </Articulo>
      </Articulos>
  </Pedido>
</Pedidos>
