=== Bcoast84/Lenguaje-de-marcas/pedidos2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Pedidos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Pedido" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Sucursal" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="DirEntrega" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                    <xs:element name="SedeCentral" type="xs:string" minOccurs="0" maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>  
              <xs:element name="NombreTrabajador" type="xs:string"/>
              <xs:element name="FechaPedido" type="xs:string"/>
              <xs:element name="ObservacionesPedido" type="xs:string" minOccurs="0"/>
              <xs:element name="PlazoRevision" type="xs:string"/>
              <xs:element name="Articulos">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Articulo" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="UnidadesPedidas" type="xs:string"/>
                          <xs:element name="PrecioUnidad" type="xs:string"/>
                          <xs:element name="ObservacionesArt" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="CodigoArt">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:pattern value="[A-Z]{3}-\d{3}"/>
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute> 
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="CodigoPedido"  use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[A-Z][A-Za-z0-9]{7}"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Bcoast84/Lenguaje-de-marcas/pedido_schema.xml
<?xml version="1.0" encoding="UTF-8"?>

<Pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pedidos2.xsd">
 
    <Pedido CodigoPedido="ABC123fc">
        <Sucursal>
            <DirEntrega>Direccion1</DirEntrega>
            <SedeCentral/>
        </Sucursal>  
        <NombreTrabajador>Juan Perez</NombreTrabajador>
        <FechaPedido>2024-03-05</FechaPedido>
        <ObservacionesPedido>Urgente</ObservacionesPedido>
        <PlazoRevision>7 días</PlazoRevision>
        <Articulos>
            <Articulo CodigoArt="ABD-123">
                <UnidadesPedidas>10</UnidadesPedidas>
                <PrecioUnidad>20.00</PrecioUnidad>
                <ObservacionesArt>Artículo de alta demanda</ObservacionesArt>
            </Articulo>
        </Articulos>
    </Pedido>
</Pedidos>
