=== Bcoast84/Lenguaje-de-marcas/Pruebas/biblioteca.dtd
<!ELEMENT biblioteca (libro+)>
    <!ELEMENT libro (titulo, autor+, editorial, genero*, edicion?, descripcion?)>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT autor (#PCDATA)>
        <!ELEMENT editorial (#PCDATA)>
        <!ELEMENT genero (#PCDATA)>
        <!ELEMENT edicion (#PCDATA)>
        <!ELEMENT descripcion (#PCDATA)>

=== Bcoast84/Lenguaje-de-marcas/Pruebas/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd"> 
<biblioteca> 
    <libro>
    <titulo>El Quijote</titulo> 
    <autor>Miguel de Cervantes</autor>
    <editorial>Planeta</editorial> 
    <genero>Narrativa</genero> 
    <edicion>45</edicion>
    </libro> 
    <libro>
    <titulo>El nombre de la rosa</titulo> 
    <autor>Umberto Eco</autor>
    <autor>Becario ayudante de Umberto Eco</autor> 
    <editorial>Luz</editorial>
    <edicion>5</edicion> 
    </libro>
</biblioteca>
