=== Bcoast84/Lenguaje-de-marcas/Pruebas/vehiculos_schema.xsd
<!-- Definición del esquema XML -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Definición del elemento coches como elemento principal -->
  <xs:element name="coches">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="vehiculo" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="marca" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="referencia" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[A-Z]{2}\d{4}[A-Z]"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== Bcoast84/Lenguaje-de-marcas/Pruebas/vehiculos.xml
<?xml version="1.0" encoding="UTF-8"?>
<coches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vehiculos_schema.xsd">

    <vehiculo referencia="AB4589R"> <marca>FORD</marca></vehiculo> 
    <vehiculo referencia="AS1235E"> <marca>SEAT</marca> </vehiculo> 
    <vehiculo referencia="UU4589H"> <marca>AUDI</marca> </vehiculo>
    <vehiculo referencia="FR4588J"> <marca>FORD</marca> </vehiculo>
</coches>
